### ISSUE TITLE
Last item clearfix

### ISSUE THREAD

**Issue by simonbook** [pinterest/cloudgrid#2]
Hi - great plugin. I want to have my pagination sit at the bottom, spanning all columns, I've tried almost everything css-wise to make the last item CLEAR across the bottom - is there something I can do to achieve this?

**Comment by xethorn** [comment]
Thanks for the feedback! 

If you look at [the example](http://rawgit.com/pinterest/cloudgrid/master/example/index.html), you will see that there's a height defined on the grid container. If you want to add pagination, the pagination should be  a sibling of the grid container.

Your structure will be something along those lines:
```
├── body
│   ├── grid container
│   │    └── [grid items]
│   └── pagination
```

Let me know if this solves your problem, I'll close the question.

**Comment by netfuelnz** [comment]
Hi - here is where im having trouble: http://simonbook.co.nz/ - you can see at the end, the pagination container, if I put this outside of the container, the items simply render over the top.

**Comment by xethorn** [comment]
Your pagination element should be __outside__ of the `blogRoll` container.

**Comment by netfuelnz** [comment]
Done, now last item overlaps it :/

**Comment by netfuelnz** [comment]
Actually, i just took the classes off it, and its ok now :) Thanks bud, you rule!

**Comment by netfuelnz** [comment]
I thought removing the class fixed it, but it only removed the background color to make it look like it was not overlapping. I've put it outside the blogroll container, since this is inside a bootstrap column, ive had to add a new row and column for it, same deal really, still overlaps.

**Comment by xethorn** [comment]
It shouldn't. You probably have a misconfiguration. Inspector is your friend :-)

**Comment by simonbook** [comment]
I might be retarded. I am using pinterest_grid - not your _cloud. I did try it but it didnt work how i hoped it would, i got an error with height of undefined. Thanks anyway,

**Comment by xethorn** [comment]
Closing the issue then since unrelated.

**Comment by dennice13** [comment]
Close it now
